---
- name: Copy good_job.service
  template:
    src: "{{ good_job_service_file }}"
    dest: /lib/systemd/system/good_job.service
    force: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0644
  register: good_job_service_file

- name: Ensure that we re-read good_job.service
  systemd:
    daemon_reload: yes
    name: "good_job"
  when: good_job_service_file.changed

- name: Enable GoodJob
  systemd:
    name: good_job
    enabled: yes
