---
- name: Deploy our Rails app
  hosts: all
  vars_files:
    - app-vars.yml
  become: true
  become_user: "{{ deploy_user }}"

  pre_tasks:
    - name: Setup app folder
      file:
        state: directory
        path: "{{ app_root_path }}"
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"

    - name: Copy rbenv-vars file
      template:
        src: ".rbenv-vars.j2"
        dest: "{{ app_root_path }}/.rbenv-vars"
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"

    - name: Make shared directories
      file: 
        path: "{{ app_shared_path }}/{{ item }}" 
        state: directory
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"
      with_items:
        - tmp
        - tmp/pids
        - tmp/cache
        - sockets
        - log
        - public
        - public/packs
        - vendor
        - vendor/bundle
        - bin
        - config
        - config/puma
        - config/credentials
        - assets
        - node_modules
    
    - name: Upload shared files
      template:
        src: "{{ item.src }}"
        dest: "{{ app_shared_path }}/{{ item.dest }}"
        owner: "{{ deploy_user }}" 
        group: "{{ deploy_group }}"
      with_items: "{{ shared_files_to_copy }}"
      tags:
        - copy

  roles:
    - role: ansistrano.deploy

    # Install puma here because the puma config is only available
    # after pulling down the app source code, which happens during the
    # ansistrano.deploy role.
    - role: puma
      tags: puma
      become: true
      become_user: root

    # Same with GoodJob, config file is within app code
    - role: goodjob
      tags: goodjob
      become: true
      become_user: root
    
    # Restart Puma, GoodJob, reload Nginx and whenever
    - role: restarts
      tags: restarts
      become: true
      become_user: root
    
