---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Create ssh key
      community.digitalocean.digital_ocean_sshkey:
        oauth_token: "{{ do_token }}" # from .env.yaml
        name: borderhound.pub
        ssh_pub_key: "{{ my_public_ssh_key }}" # from .env.yaml
        state: present
      register: ssh_key
    
    - debug:
        msg: "Create SSH key result: {{ ssh_key }}"

    - name: Create a new droplet if not already created
      community.digitalocean.digital_ocean_droplet:
        state: active
        name: borderhound
        unique_name: true
        oauth_token: "{{ do_token }}" # from .env.yaml
        size: s-2vcpu-2gb-intel
        region: tor1
        image: ubuntu-20-04-x64
        wait_timeout: 500
        ssh_keys:
          - "{{ ssh_key.data.ssh_key.id }}"
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"

    - name: Create a Floating IP assigned to new droplet
      community.digitalocean.digital_ocean_floating_ip:
        state: present
        oauth_token: "{{ do_token }}"
        droplet_id: "{{ my_droplet.data.droplet.id }}"
      register: floating_ip

    - debug:
        msg: "Floating IP completed_at: {{ floating_ip.data }}"
