---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Get Basic droplet Size Slug 
      community.digitalocean.digital_ocean_size_info:
        oauth_token: "{{ do_token }}" # from .env.yaml
      register: resp_out
    - debug: var=resp_out
    - set_fact:
        size_slug: "{{ item.slug }}"
      loop: "{{ resp_out.data | community.general.json_query(name) }}"
      vars:
        # name: "[?description==`Basic`]"
        name: "[?memory==`2048`]"
    - debug:
        var: size_slug
