---
- hosts: all
  become: true

  vars_files:
    - app-vars.yml
  tasks:
    - debug: msg="Variable 'app_name' is set to {{ app_name }}"
  
  roles: 
    - role: common
    - role: user
    - role: ssh
    - role: ruby
      tags: ruby
    - role: nodejs
      tags: nodejs
    - role: yarn
      tags: nodejs
    - role: postgresql
      tags: postgresql
    - role: certbot
      tags: certbot
    - role: nginx
      tags: nginx
    - role: logrotate
      tags: logrotate
