---
- hosts: all
  become: true

  vars_files:
    - app-vars.yml
  
  roles: 
    - role: common
      tags: common
    - role: environment
      tags: environment
    - role: user
    - role: ssh
    - role: ruby
      tags: ruby
    - role: nodejs
      tags: nodejs
    - role: yarn
      tags: nodejs
    - role: postgresql
      tags: postgresql
    - role: nginx
      tags: nginx
    #- role: certbot
    #  tags: certbot
    - role: logrotate
      tags: logrotate
