---
- hosts: all
  become: true

  vars_files:
    - app-vars.yml
  
  roles: 
    - role: common
      tags: common
    - role: user
    - role: environment
      tags: environment
    - role: ssh
    - role: ruby
      tags: ruby
    - role: nodejs
      tags: nodejs
    - role: yarn
      tags: nodejs
    - role: postgresql
      tags: postgresql
    - role: certbot
      tags: certbot
      when: within_virtual_box == false
    - role: self_signed
      tags: self_signed
      when: within_virtual_box == true
    - role: nginx
      tags: nginx
    - role: logrotate
      tags: logrotate
    - role: goaccess
      tags: goaccess
    - role: fail2ban
      tags: fail2ban
    - role: ufw
      tags: ufw
    - role: swapfile
      tags: swapfile
    - role: pgbackup
      tags: pgbackup
