---
- name: Enable .bashrc vim bindings
  lineinfile:
    dest: "/etc/bash.bashrc"
    line: "set -o vi"
    state: present

- name: Enable /etc/inputrc vim bindings
  lineinfile:
    dest: "/etc/inputrc"
    line: "{{ item.line }}"
    state: present
  loop:
  - { line: 'set keymap vi' }
  - { line: 'set editing-mode vi' }

- name: Enable /etc/{{ deploy_user }}/.inputrc vim bindings
  become: true
  become_user: "{{ deploy_user }}" 
  lineinfile:
    dest: "/home/{{ deploy_user }}/.inputrc"
    line: "{{ item.line }}"
    state: present
    create: yes
  loop:
  - { line: 'set keymap vi' }
  - { line: 'set editing-mode vi' }

- name: Set timezone to {{ timezone }}
  when: ansible_date_time.tz != timezone
  command: timedatectl set-timezone {{ timezone_location }}

- name: Copy screenrc
  copy:
    src: screenrc
    dest: /etc

- name: Copy vimrc
  copy:
    src: vimrc
    dest: /etc/vim
