---
- name: register lsb release
  command: lsb_release -cs
  register: lsb_release

- name: Install the dependencies
  apt:
    name: ['libgeoip-dev', 'libncursesw5-dev', 'libmaxminddb-dev', 'libtokyocabinet-dev', 'libssl-dev', 'apt-transport-https']
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key: url=https://deb.goaccess.io/gnugpg.key state=present

- apt_repository: repo='deb http://deb.goaccess.io/ {{ lsb_release.stdout }} main' state=present filename='goaccess'

- name: install goaccess
  apt: name=goaccess state=latest update_cache=yes