---
- name: Ensure that nginx is stopped
  service: 
    name: nginx
    state: stopped

- name: Check & get new certificate
  include_tasks: cert.yml
  loop: "{{ certbot_domains }}"
  loop_control:
    loop_var: domain

- name: Add certbot renewal cronjob
  cron: name="renew letsencrypt certificates" hour="0" minute="0" job="/bin/bash certbot renew --non-interactive --quiet --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start'"
