---
# - name: add univere repo ?
#   apt_repository:
#     repo: universe

- name: Install certbot
  apt:
    name:
      - certbot
    state: present
    force: yes
    update_cache: yes

- name: Ensure that nginx is stopped
  service:
    name: nginx
    state: stopped

- name: Check & get new certificate
  include_tasks: cert.yml
  loop: "{{ certbot_domains }}"
  loop_control:
    loop_var: domain

- name: Add certbot renewal cronjob
  cron: name="renew letsencrypt certificates" hour="2" minute="42" job="certbot renew --non-interactive --quiet --standalone --pre-hook 'service nginx stop' --post-hook 'service nginx start'"