---

all:
  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: ~/.ssh/borderhound
    ansible_python_interpreter: /usr/bin/python3
    within_virtual_box: false
  hosts:
    borderhound.com
